/**
 * @description       : 
 * @author            : Sangram Keshari Upadhyaya
 * @group             : 
 * @last modified on  : 25-05-2025
 * @last modified by  : Sangram Keshari Upadhyaya
 * Modifications Log
 * Ver   Date         Author                      Modification
 * 1.0   25-05-2025   Sangram Keshari Upadhyaya   Initial Version
**/
public with sharing class ApexTut_07_Extends {
    
    // Extends
    // A class can extend another class - meaning it inherits the propertie of that class.
    // We can define a class using the virtual keyword if we want it to be extended.
    // We can use this class using extends keyword in the class that needs to inherit the properties.
    // To use the methods of the extended class, we can use the override method
    // To override a method it cannot be static and should have virtual keyword
    // Note :: We can only extend one class, not more than that.

    // Example : Employee & Manager classes

}