/**
 * @description       : 
 * @author            : Sangram Keshari Upadhyaya
 * @group             : 
 * @last modified on  : 25-05-2025
 * @last modified by  : Sangram Keshari Upadhyaya
 * Modifications Log
 * Ver   Date         Author                      Modification
 * 1.0   25-05-2025   Sangram Keshari Upadhyaya   Initial Version
**/
public class Manager extends Employee {

    public static void handleTeam() {

    }

    public static void handleEscalations() {

    }

    public static void handleDeliverability() {

    }

    public static void handleAppraisals() {

    }

    public override void markAttendence() {
        System.debug('Mark attendence for the Manager, who is also an Employee!');
    }

}